In [2]:
m_prefs=[
[3,2,1],
[2,3,1],
[1,3,2],
[2,1,3]
]

f_prefs=[
[1,2],
[1,4],
[3,1,2]
]

3-element Array{Array{Int64,1},1}:
 [1,2]  
 [1,4]  
 [3,1,2]

In [7]:
#beginning
f_matched = zeros(Int, 3)

3-element Array{Int64,1}:
 0
 0
 0

In [5]:
#who is unmatched?
m_unmatched=trues(4)

4-element BitArray{1}:
 true
 true
 true
 true

In [8]:
#選好の一番をみる
m_pointers = ones(Int, 4)

4-element Array{Int64,1}:
 1
 1
 1
 1

In [ ]:
#there exists unmatched male
while any(m_unmatched)
    for m in 1:4
    if m_unmatched[m]
            #propose
            f = m_prefs[m][m_pointers[m]]
            if m in f_prefs[f]
                if f_matched[f] == 0
                    f_matched[f] = m
                    m_unmatched[m] = false
                    m_pointers[m] += 1
                    
                
                    #propose
                    if m_pointers[m] == length(m_prefs[m])
                        m_unmatched[m] = false
                    end
                else
                    current_m = f_matched[f]

                    if findfirst(f_prefs[f], current_m) > findfirst(f_prefs[f], m)
                        f_matched[f] = m
                        m_unmatched[m] = false
                        m_pointers[m] += 1
                        m_unmatched[current_m] = true
                        
                        
                        #propose
                        if m_pointers[m] == length(m_prefs[m])
                            m_unmatched[m] = false
                        end
                    end
               
                end
                
            else
                
                if m_pointers[m] == length(m_prefs[m])
                            m_unmatched[m] = false
                else
                    m_pointers[m] += 1
                end
                
            end
        end
    end
end   