In [2]:
m_prefs=[
[3,2,1],
[2,3,1],
[1,3,2],
[2,1,3]
]

f_prefs=[
[1,2],
[1,4],
[3,1,2]
]

3-element Array{Array{Int64,1},1}:
 [1,2]  
 [1,4]  
 [3,1,2]

In [7]:
#beginning
f_matched = zeros(Int, 3)

3-element Array{Int64,1}:
 0
 0
 0

In [5]:
#who is unmatched?
m_unmatched=trues(4)

4-element BitArray{1}:
 true
 true
 true
 true

In [8]:
#選好の一番をみる
m_pointers = ones(Int, 4)

4-element Array{Int64,1}:
 1
 1
 1
 1

In [3]:
module MyMatching
    export my_deferred_acceptance

    function my_deferred_acceptance(m_prefs, f_prefs)
        num_m = length(m_prefs)
        num_f = length(f_prefs)
        f_matched = zeros(Int, num_f)
        m_unmatched = collect(1:num_m)
        m_pointers = ones(Int, num_m)

        while length(m_unmatched) > 0
            m = m_unmatched[1]
            if length(m_prefs[m]) < m_pointers[m]
                shift!(m_unmatched)
                continue
            end
            f = m_prefs[m][m_pointers[m]]
            if m in f_prefs[f] #if m is favorable to f
                current_m = f_matched[f] 
                if current_m == 0 #if f is not married
                    f_matched[f] = m
                    shift!(m_unmatched)
                    continue
                elseif findfirst(f_prefs[f], current_m) > findfirst(f_prefs[f], m) #if m is more preferred
                    f_matched[f] = m
                    m_unmatched[1] = current_m
                    m_pointers[current_m] += 1
                    continue
                end
            end
            m_pointers[m] += 1
        end

        m_matched = Int[findfirst(f_matched, i) for i in 1:num_m]
        return m_matched, f_matched
    end
end

MyMatching