金正賢です。
MyMatchingのコードは以下より
https://github.com/ellenjunghyunkim/MyMatching.jl/blob/master/src/MyMatching.jl
my_deferred_acceptanceのデモです。

In [1]:
m_prefs=[
[3,2,1],
[2,3,1],
[1,3,2],
[2,1,3]
]

f_prefs=[
[1,2],
[1,4],
[3,1,2]
]

3-element Array{Array{Int64,1},1}:
 [1,2]  
 [1,4]  
 [3,1,2]

In [2]:
#beginning
f_matched = zeros(Int, 3)

3-element Array{Int64,1}:
 0
 0
 0

In [3]:
#who is unmatched?
m_unmatched=trues(4)

4-element BitArray{1}:
 true
 true
 true
 true

In [4]:
#選好の一番をみる
m_pointers = ones(Int, 4)

4-element Array{Int64,1}:
 1
 1
 1
 1

In [5]:
using MyMatching

In [6]:
m_prefswiki = [[1, 2, 3, 4], [3, 2, 1, 4], [1, 2, 4, 3], [3, 1,  4, 2]]
f_prefswiki = [[1, 2, 3, 4], [2, 1, 4, 3], [2, 3, 1, 4], [1, 4, 3, 2]];

In [7]:
Pkg.test("MyMatching")

INFO: Testing MyMatching


Test Summary:               | Pass  Total
  Testing deferred acceptance |   12     12


INFO: MyMatching tests passed


自分で作った my_deferred_acceptance を使っててる例を試してみます

In [8]:
m_prefswiki = [[1, 2, 3, 4], [3, 2, 1, 4], [1, 2, 4, 3], [3, 1,  4, 2]]
f_prefswiki = [[1, 2, 3, 4], [2, 1, 4, 3], [2, 3, 1, 4], [1, 4, 3, 2]];

In [9]:
my_deferred_acceptance(m_prefswiki, f_prefswiki)

([1,3,2,4],[1,3,2,4])

In [10]:
m_prefskadai = [[3], [3, 2, 1], [1, 3, 2], [3, 1]]
f_prefskadai = [[2, 3], [2, 3, 4, 1], [4, 1, 2]];

In [11]:
my_deferred_acceptance(m_prefskadai, f_prefskadai)

([0,2,1,3],[3,2,4])